/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv functions/cloudflare-env.d.ts` (hash: d84610d73522418f96a0cea708e4282d)
interface __BaseEnv_CloudflareEnv {
	SEARCH_RATE_LIMIT_DB: D1Database;
	SEARCH_INDEX: VectorizeIndex;
	AI: Ai;
	SEARCH_ENABLED: "true";
	SEARCH_MIN_SCORE: "0.40";
}
declare namespace Cloudflare {
	interface PreviewEnv {
		SEARCH_RATE_LIMIT_DB: D1Database;
		SEARCH_INDEX: VectorizeIndex;
		AI: Ai;
		SEARCH_ENABLED: "true";
		SEARCH_MIN_SCORE: "0.40";
	}
	interface ProductionEnv {
		SEARCH_RATE_LIMIT_DB: D1Database;
		SEARCH_INDEX: VectorizeIndex;
		AI: Ai;
		SEARCH_ENABLED: "true";
		SEARCH_MIN_SCORE: "0.40";
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
