/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv functions/cloudflare-env.d.ts` (hash: ed03da852c1689e7fc218f0acabd8b50)
interface __BaseEnv_CloudflareEnv {
  SEARCH_RATE_LIMIT_DB: D1Database;
  SEARCH_EMBEDDING_MODEL: "@cf/baai/bge-m3";
  SEARCH_EMBEDDING_DIMENSIONS: "1024";
  SEARCH_ENABLED: "false" | "true";
  SEARCH_MIN_SCORE: "0.40";
  SEARCH_INDEX?: VectorizeIndex;
  AI?: Ai;
}
declare namespace Cloudflare {
  interface PreviewEnv {
    SEARCH_RATE_LIMIT_DB: D1Database;
    SEARCH_EMBEDDING_MODEL: "@cf/baai/bge-m3";
    SEARCH_EMBEDDING_DIMENSIONS: "1024";
    SEARCH_ENABLED: "false";
    SEARCH_MIN_SCORE: "0.40";
  }
  interface ProductionEnv {
    SEARCH_RATE_LIMIT_DB: D1Database;
    SEARCH_INDEX: VectorizeIndex;
    AI: Ai;
    SEARCH_EMBEDDING_MODEL: "@cf/baai/bge-m3";
    SEARCH_EMBEDDING_DIMENSIONS: "1024";
    SEARCH_ENABLED: "true";
    SEARCH_MIN_SCORE: "0.40";
  }
  interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
