/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv functions/cloudflare-env.d.ts` (hash: d8fb99ebc7b6b9a06f515dddff1353a0)
interface __BaseEnv_CloudflareEnv {
	SEARCH_RATE_LIMIT_DB: D1Database;
	SEARCH_INDEX: VectorizeIndex;
	OPENAI_EMBEDDING_MODEL: "text-embedding-3-large";
	OPENAI_EMBEDDING_DIMENSIONS: "1536";
	SEARCH_ENABLED: "true";
	SEARCH_MIN_SCORE: "0.40";
}
declare namespace Cloudflare {
	interface PreviewEnv {
		SEARCH_RATE_LIMIT_DB: D1Database;
		SEARCH_INDEX: VectorizeIndex;
		OPENAI_EMBEDDING_MODEL: "text-embedding-3-large";
		OPENAI_EMBEDDING_DIMENSIONS: "1536";
		SEARCH_ENABLED: "true";
		SEARCH_MIN_SCORE: "0.40";
	}
	interface ProductionEnv {
		SEARCH_RATE_LIMIT_DB: D1Database;
		SEARCH_INDEX: VectorizeIndex;
		OPENAI_EMBEDDING_MODEL: "text-embedding-3-large";
		OPENAI_EMBEDDING_DIMENSIONS: "1536";
		SEARCH_ENABLED: "true";
		SEARCH_MIN_SCORE: "0.40";
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
